### ISSUE TITLE
carsharing container fails to start after last PR

### ISSUE THREAD

**Issue by RudiThoeni** [noi-techpark/odh-mentor-otp#127]
Hi,

After the last PR (https://github.com/noi-techpark/odh-mentor-otp/pull/126) there is something wrong with the carsharing module.
The docker container for carsharing  is always restarting.

Here the application log
[otplog.txt](https://github.com/noi-techpark/odh-mentor-otp/files/7719623/otplog.txt)

for carsharing:
```
carsharing_1  | /home/index.js:82
carsharing_1  |     const brand = _.trim(car.smetadata?.brand);
carsharing_1  |                                        ^
carsharing_1  |
carsharing_1  | SyntaxError: Unexpected token '.'
carsharing_1  |     at wrapSafe (internal/modules/cjs/loader.js:1054:16)
carsharing_1  |     at Module._compile (internal/modules/cjs/loader.js:1102:27)
carsharing_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
carsharing_1  |     at Module.load (internal/modules/cjs/loader.js:986:32)
carsharing_1  |     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
carsharing_1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
carsharing_1  |     at internal/main/run_main_module.js:17:47
carsharing_1  | /home/index.js:82
carsharing_1  |     const brand = _.trim(car.smetadata?.brand);
carsharing_1  |                                        ^
carsharing_1  |
carsharing_1  | SyntaxError: Unexpected token '.'
carsharing_1  |     at wrapSafe (internal/modules/cjs/loader.js:1054:16)
carsharing_1  |     at Module._compile (internal/modules/cjs/loader.js:1102:27)
carsharing_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
carsharing_1  |     at Module.load (internal/modules/cjs/loader.js:986:32)
carsharing_1  |     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
carsharing_1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
carsharing_1  |     at internal/main/run_main_module.js:17:47
carsharing_1  | /home/index.js:82
carsharing_1  |     const brand = _.trim(car.smetadata?.brand);
carsharing_1  |                                        ^
carsharing_1  |
carsharing_1  | SyntaxError: Unexpected token '.'
carsharing_1  |     at wrapSafe (internal/modules/cjs/loader.js:1054:16)
carsharing_1  |     at Module._compile (internal/modules/cjs/loader.js:1102:27)
carsharing_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
carsharing_1  |     at Module.load (internal/modules/cjs/loader.js:986:32)
carsharing_1  |     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
carsharing_1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
carsharing_1  |     at internal/main/run_main_module.js:17:47
carsharing_1  | /home/index.js:82
carsharing_1  |     const brand = _.trim(car.smetadata?.brand);
carsharing_1  |                                        ^
carsharing_1  |
carsharing_1  | SyntaxError: Unexpected token '.'
carsharing_1  |     at wrapSafe (internal/modules/cjs/loader.js:1054:16)
carsharing_1  |     at Module._compile (internal/modules/cjs/loader.js:1102:27)
carsharing_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
carsharing_1  |     at Module.load (internal/modules/cjs/loader.js:986:32)
carsharing_1  |     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
carsharing_1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
carsharing_1  |     at internal/main/run_main_module.js:17:47
carsharing_1  | /home/index.js:82
carsharing_1  |     const brand = _.trim(car.smetadata?.brand);
carsharing_1  |                                        ^
carsharing_1  |
carsharing_1  | SyntaxError: Unexpected token '.'
carsharing_1  |     at wrapSafe (internal/modules/cjs/loader.js:1054:16)
carsharing_1  |     at Module._compile (internal/modules/cjs/loader.js:1102:27)
carsharing_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
carsharing_1  |     at Module.load (internal/modules/cjs/loader.js:986:32)
carsharing_1  |     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
carsharing_1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
carsharing_1  |     at internal/main/run_main_module.js:17:47
carsharing_1  | /home/index.js:82
carsharing_1  |     const brand = _.trim(car.smetadata?.brand);
carsharing_1  |                                        ^
carsharing_1  |
carsharing_1  | SyntaxError: Unexpected token '.'
carsharing_1  |     at wrapSafe (internal/modules/cjs/loader.js:1054:16)
carsharing_1  |     at Module._compile (internal/modules/cjs/loader.js:1102:27)
carsharing_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
carsharing_1  |     at Module.load (internal/modules/cjs/loader.js:986:32)
carsharing_1  |     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
carsharing_1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
carsharing_1  |     at internal/main/run_main_module.js:17:47
carsharing_1  | /home/index.js:82
carsharing_1  |     const brand = _.trim(car.smetadata?.brand);
carsharing_1  |                                        ^
carsharing_1  |
carsharing_1  | SyntaxError: Unexpected token '.'
carsharing_1  |     at wrapSafe (internal/modules/cjs/loader.js:1054:16)
carsharing_1  |     at Module._compile (internal/modules/cjs/loader.js:1102:27)
carsharing_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
carsharing_1  |     at Module.load (internal/modules/cjs/loader.js:986:32)
carsharing_1  |     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
carsharing_1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
carsharing_1  |     at internal/main/run_main_module.js:17:47
carsharing_1  | /home/index.js:82
carsharing_1  |     const brand = _.trim(car.smetadata?.brand);
carsharing_1  |                                        ^
carsharing_1  |
carsharing_1  | SyntaxError: Unexpected token '.'
carsharing_1  |     at wrapSafe (internal/modules/cjs/loader.js:1054:16)
carsharing_1  |     at Module._compile (internal/modules/cjs/loader.js:1102:27)
carsharing_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
carsharing_1  |     at Module.load (internal/modules/cjs/loader.js:986:32)
carsharing_1  |     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
carsharing_1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
carsharing_1  |     at internal/main/run_main_module.js:17:47
carsharing_1  | /home/index.js:82
carsharing_1  |     const brand = _.trim(car.smetadata?.brand);
carsharing_1  |                                        ^
carsharing_1  |
carsharing_1  | SyntaxError: Unexpected token '.'
carsharing_1  |     at wrapSafe (internal/modules/cjs/loader.js:1054:16)
carsharing_1  |     at Module._compile (internal/modules/cjs/loader.js:1102:27)
carsharing_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
carsharing_1  |     at Module.load (internal/modules/cjs/loader.js:986:32)
carsharing_1  |     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
carsharing_1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
carsharing_1  |     at internal/main/run_main_module.js:17:47
carsharing_1  | /home/index.js:82
carsharing_1  |     const brand = _.trim(car.smetadata?.brand);
carsharing_1  |                                        ^
carsharing_1  |
carsharing_1  | SyntaxError: Unexpected token '.'
carsharing_1  |     at wrapSafe (internal/modules/cjs/loader.js:1054:16)
carsharing_1  |     at Module._compile (internal/modules/cjs/loader.js:1102:27)
carsharing_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
carsharing_1  |     at Module.load (internal/modules/cjs/loader.js:986:32)
carsharing_1  |     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
carsharing_1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
carsharing_1  |     at internal/main/run_main_module.js:17:47
carsharing_1  | /home/index.js:82
carsharing_1  |     const brand = _.trim(car.smetadata?.brand);
carsharing_1  |                                        ^
carsharing_1  |
carsharing_1  | SyntaxError: Unexpected token '.'
carsharing_1  |     at wrapSafe (internal/modules/cjs/loader.js:1054:16)
carsharing_1  |     at Module._compile (internal/modules/cjs/loader.js:1102:27)
carsharing_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
carsharing_1  |     at Module.load (internal/modules/cjs/loader.js:986:32)
carsharing_1  |     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
carsharing_1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
carsharing_1  |     at internal/main/run_main_module.js:17:47
carsharing_1  | /home/index.js:82
carsharing_1  |     const brand = _.trim(car.smetadata?.brand);
carsharing_1  |                                        ^
carsharing_1  |
carsharing_1  | SyntaxError: Unexpected token '.'
carsharing_1  |     at wrapSafe (internal/modules/cjs/loader.js:1054:16)
carsharing_1  |     at Module._compile (internal/modules/cjs/loader.js:1102:27)
carsharing_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
carsharing_1  |     at Module.load (internal/modules/cjs/loader.js:986:32)
carsharing_1  |     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
carsharing_1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
carsharing_1  |     at internal/main/run_main_module.js:17:47
carsharing_1  | /home/index.js:82
carsharing_1  |     const brand = _.trim(car.smetadata?.brand);
carsharing_1  |                                        ^
carsharing_1  |
carsharing_1  | SyntaxError: Unexpected token '.'
carsharing_1  |     at wrapSafe (internal/modules/cjs/loader.js:1054:16)
carsharing_1  |     at Module._compile (internal/modules/cjs/loader.js:1102:27)
carsharing_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
carsharing_1  |     at Module.load (internal/modules/cjs/loader.js:986:32)
carsharing_1  |     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
carsharing_1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
carsharing_1  |     at internal/main/run_main_module.js:17:47
carsharing_1  | /home/index.js:82
carsharing_1  |     const brand = _.trim(car.smetadata?.brand);
carsharing_1  |                                        ^
carsharing_1  |
carsharing_1  | SyntaxError: Unexpected token '.'
carsharing_1  |     at wrapSafe (internal/modules/cjs/loader.js:1054:16)
carsharing_1  |     at Module._compile (internal/modules/cjs/loader.js:1102:27)
carsharing_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
carsharing_1  |     at Module.load (internal/modules/cjs/loader.js:986:32)
carsharing_1  |     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
carsharing_1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
carsharing_1  |     at internal/main/run_main_module.js:17:47
carsharing_1  | /home/index.js:82
carsharing_1  |     const brand = _.trim(car.smetadata?.brand);
carsharing_1  |                                        ^
carsharing_1  |
carsharing_1  | SyntaxError: Unexpected token '.'
carsharing_1  |     at wrapSafe (internal/modules/cjs/loader.js:1054:16)
carsharing_1  |     at Module._compile (internal/modules/cjs/loader.js:1102:27)
carsharing_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
carsharing_1  |     at Module.load (internal/modules/cjs/loader.js:986:32)
carsharing_1  |     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
carsharing_1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
carsharing_1  |     at internal/main/run_main_module.js:17:47
carsharing_1  | /home/index.js:82
carsharing_1  |     const brand = _.trim(car.smetadata?.brand);
carsharing_1  |                                        ^
carsharing_1  |
carsharing_1  | SyntaxError: Unexpected token '.'
carsharing_1  |     at wrapSafe (internal/modules/cjs/loader.js:1054:16)
carsharing_1  |     at Module._compile (internal/modules/cjs/loader.js:1102:27)
carsharing_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
carsharing_1  |     at Module.load (internal/modules/cjs/loader.js:986:32)
carsharing_1  |     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
carsharing_1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
carsharing_1  |     at internal/main/run_main_module.js:17:47
carsharing_1  | /home/index.js:82
carsharing_1  |     const brand = _.trim(car.smetadata?.brand);
carsharing_1  |                                        ^
carsharing_1  |
carsharing_1  | SyntaxError: Unexpected token '.'
carsharing_1  |     at wrapSafe (internal/modules/cjs/loader.js:1054:16)
carsharing_1  |     at Module._compile (internal/modules/cjs/loader.js:1102:27)
carsharing_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
carsharing_1  |     at Module.load (internal/modules/cjs/loader.js:986:32)
carsharing_1  |     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
carsharing_1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
carsharing_1  |     at internal/main/run_main_module.js:17:47
```

**Comment by stefanocudini** [comment]
@RudiThoeni I'll solve it asap
