### ISSUE TITLE
CORS problems with geocoder

### ISSUE THREAD

**Issue by bertolla** [noi-techpark/odh-mentor-otp#44]
![cors](https://user-images.githubusercontent.com/3582457/111762909-d59ed300-88a1-11eb-9324-572d8503464d.png)

**Comment by bertolla** [comment]
This is the error message:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received null
    at validateString (internal/validators.js:120:11)
    at Url.parse (url.js:159:3)
    at Object.urlParse [as parse] (url.js:154:13)
    at /home/config.js:70:11
    at /home/node_modules/lodash/lodash.js:13469:38
    at /home/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/home/node_modules/lodash/lodash.js:3032:24)
    at Function.mapValues (/home/node_modules/lodash/lodash.js:13468:7)
    at Object.<anonymous> (/home/config.js:67:25)
    at Module._compile (internal/modules/cjs/loader.js:1138:30) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by stefanocudini** [comment]
@bertolla about this.
the error shown now should not appear
But I believe that the environment variable API_HOST,API_PORT is not passed to the geocoder service:

API_HOST should be the OTP service which must also be reachable from the geocoder:

I'm not sure if this is enough you could verify that the environment variables in the running container(geocoder) are set
https://github.com/noi-techpark/odh-mentor-otp/blob/development/infrastructure/docker-compose.run.execute.yml#L45
